name: myevn
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.4.26=hecd8cb5_0
  - certifi=2022.6.15=py310hecd8cb5_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py310hca72f7f_0
  - mkl_fft=1.3.1=py310hf879493_0
  - mkl_random=1.2.2=py310hc081a56_0
  - ncurses=6.3=hca72f7f_2
  - numpy=1.22.3=py310hdcd3fac_0
  - numpy-base=1.22.3=py310hfd2de13_0
  - openssl=1.1.1p=hca72f7f_0
  - pip=21.2.4=py310hecd8cb5_0
  - python=3.10.4=hdfd78df_0
  - readline=8.1.2=hca72f7f_1
  - setuptools=61.2.0=py310hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=h707629a_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=hca72f7f_1
  - zlib=1.2.12=h4dc903c_2
prefix: /Users/senapeksin/opt/anaconda3/envs/myevn
